# Generated by Django 4.1.1 on 2022-09-28 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Releve',
            fields=[
                ('id_releve', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_releve', models.CharField(max_length=255)),
                ('date_releve', models.DateField()),
                ('etat_releve', models.BooleanField()),
                ('nb_tread_releve', models.IntegerField()),
                ('nb_comment_releve', models.IntegerField()),
                ('id_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.projects')),
            ],
        ),
    ]
