# Generated by Django 4.1.1 on 2022-09-28 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_releve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_project',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='releve',
            name='date_releve',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
