# Generated by Django 4.1.1 on 2022-09-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_projects_date_project_alter_releve_date_releve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url_site',
            field=models.TextField(blank=True),
        ),
    ]
