# Generated by Django 4.1.1 on 2022-09-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_projects_url_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releve',
            name='etat_releve',
            field=models.BooleanField(null=True),
        ),
    ]
