# Generated by Django 4.1.1 on 2022-09-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_releve_id_members_remove_releve_id_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releve',
            name='id_members',
        ),
        migrations.RemoveField(
            model_name='releve',
            name='id_project',
        ),
        migrations.AddField(
            model_name='releve',
            name='id_members',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.members'),
        ),
        migrations.AddField(
            model_name='releve',
            name='id_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.projects'),
        ),
    ]
